-- Active: 1746548129687@@127.0.0.1@5432@tokilake
-- Generated by the database client.
CREATE TABLE IF NOT EXISTS clients(
    id SERIAL NOT NULL,
    "type" text NOT NULL,
    namespace text NOT NULL,
    api_base text,
    api_key text[],
    public boolean DEFAULT false,
    PRIMARY KEY(id)
);
CREATE UNIQUE INDEX clients_name_key ON public.clients USING btree (namespace);

-- Generated by the database client.
CREATE TABLE IF NOT EXISTS models(
    id SERIAL NOT NULL,
    client_id integer NOT NULL,
    name text NOT NULL,
    PRIMARY KEY(id),
    CONSTRAINT models_client_id_fkey FOREIGN key(client_id) REFERENCES clients(id)
);

